const fs = require('fs');
const path = require('path');

// Read frontend/.env file
const envPath = path.join(__dirname, '.env');
if (!fs.existsSync(envPath)) {
  console.error('.env file not found in frontend directory!');
  process.exit(1);
}

const envContent = fs.readFileSync(envPath, 'utf8');
const env = {};
envContent.split('\n').forEach(line => {
  const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
  if (match) {
    let value = match[2] || '';
    value = value.replace(/^['"](.*)['"]$/, '$1').trim();
    env[match[1]] = value;
  }
});

const configJsContent = `// Auto-generated by frontend/generate-config.js from frontend/.env
window.RESQNET_CONFIG = {
  BACKEND_URL: "${env['RESQNET_BACKEND_URL'] || ''}",
  WS_URL: "${env['RESQNET_WS_URL'] || ''}",
  SESSION_TOKEN_URL: "${env['RESQNET_SESSION_TOKEN_URL'] || ''}"
};

window.firebaseConfig = {
  apiKey: "${env['FIREBASE_API_KEY'] || ''}",
  authDomain: "${env['FIREBASE_AUTH_DOMAIN'] || ''}",
  projectId: "${env['FIREBASE_PROJECT_ID'] || ''}",
  storageBucket: "${env['FIREBASE_STORAGE_BUCKET'] || ''}",
  messagingSenderId: "${env['FIREBASE_MESSAGING_SENDER_ID'] || ''}",
  appId: "${env['FIREBASE_APP_ID'] || ''}",
  measurementId: "${env['FIREBASE_MEASUREMENT_ID'] || ''}"
};
`;

// Write to all three dashboard directories
const targets = [
  path.join(__dirname, 'user_dashboard', 'config.js'),
  path.join(__dirname, 'responder_dashboard', 'config.js'),
  path.join(__dirname, '..', 'Trial_Dashboard', 'config.js')
];

targets.forEach(target => {
  if (fs.existsSync(path.dirname(target))) {
    fs.writeFileSync(target, configJsContent, 'utf8');
    console.log('Successfully generated ' + target);
  }
});
